// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

type Config struct {
	// Database corresponds to the JSON schema field "database".
	Database *ConfigDatabase `json:"database,omitempty" yaml:"database,omitempty" mapstructure:"database,omitempty"`

	// Env corresponds to the JSON schema field "env".
	Env *string `json:"env,omitempty" yaml:"env,omitempty" mapstructure:"env,omitempty"`

	// ListenPort corresponds to the JSON schema field "listen_port".
	ListenPort *float64 `json:"listen_port,omitempty" yaml:"listen_port,omitempty" mapstructure:"listen_port,omitempty"`
}

type ConfigDatabase struct {
	// Pass corresponds to the JSON schema field "pass".
	Pass string `json:"pass" yaml:"pass" mapstructure:"pass"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`

	// User corresponds to the JSON schema field "user".
	User string `json:"user" yaml:"user" mapstructure:"user"`
}
